language: csharp  
mono: none
dotnet: 2.1.0
dist: trusty
env:  
  - IS_TESTING_ENVIRONMENT=true
os:  
  - linux
branches:  
  only:
    - master
script:  
  - dotnet --info
  - dotnet restore
  - dotnet test tests/RazorLight.Tests/RazorLight.Tests.csproj