language: csharp  
mono: none
dotnet: 3.0.0
dist: trusty

before_install:
  - wget -q https://packages.microsoft.com/config/ubuntu/18.04/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
  - sudo dpkg -i packages-microsoft-prod.deb
  - sudo add-apt-repository universe
  - sudo apt-get update
  - sudo apt-get install apt-transport-https
  - sudo apt-get update
env:  
  - IS_TESTING_ENVIRONMENT=true
os:  
  - linux
branches:  
  only:
    - master
script:  
  - dotnet --info
  - dotnet restore
  - dotnet test tests/RazorLight.Tests/RazorLight.Tests.csproj